//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NG_MVC_FIltering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderManager
    {
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobileNo { get; set; }
        public string OrderedItem { get; set; }
        public int OrderedQuantity { get; set; }
        public string SalesAgentName { get; set; }
    }
}
